; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Sun Aug 28 2022 17:41:03 GMT+0200 (Mitteleuropäische Sommerzeit)

M18